language: Rust
cache: cargo
sudo: false
rust:
- nightly
- beta
- stable
before_script:
- export PATH=$HOME/.cargo/bin:$PATH
- type rustfmt || cargo +nightly install rustfmt-nightly
script:
- cargo test
env:
  global:
  - RUST_BACKTRACE=1
